function env-sync --description "Sync API keys from Bitwarden to environment"
    # Parse arguments
    set -l force_overwrite false
    for arg in $argv
        switch $arg
            case --force -f
                set force_overwrite true
            case --help -h
                echo "Sync API keys from Bitwarden to environment"
                echo ""
                echo "Usage: env-sync [options]"
                echo ""
                echo "Options:"
                echo "  -f, --force    Force refresh all variables (even unchanged)"
                echo "  -h, --help     Show this help message"
                echo ""
                echo "Behavior:"
                echo "  - New variables: Always set"
                echo "  - Changed values: Auto-updated (smart sync)"
                echo "  - Unchanged values: Skipped"
                echo "  - All values persisted to ~/.config/fish/conf.d/env-sync-vars.fish"
                return 0
        end
    end

    if not command -v bw >/dev/null
        echo (set_color red)"Error: Bitwarden CLI (bw) not found"(set_color normal)
        return 1
    end
    if not command -v jq >/dev/null
        echo (set_color red)"Error: jq not found"(set_color normal)
        return 1
    end

    # Unlock Bitwarden if needed
    if not set -q BW_SESSION
        or test -z "$BW_SESSION"
        echo (set_color -o ff9900)"Unlocking Bitwarden"(set_color normal)
        set -l unlock_out (bw unlock --raw 2>/dev/null)
        if test $status -ne 0
            or test -z "$unlock_out"
            echo (set_color red)"Error: failed to unlock Bitwarden"(set_color normal)
            return 1
        end
        set -gx BW_SESSION $unlock_out
    end

    set -l item_json (bw get item "API Keys" --session "$BW_SESSION" 2>/dev/null)
    if test $status -ne 0
        or test -z "$item_json"
        echo (set_color red)"Error: could not read Bitwarden item 'API Keys'"(set_color normal)
        bw lock --session "$BW_SESSION" >/dev/null 2>&1
        set -e BW_SESSION
        return 1
    end

    set -l field_names (echo $item_json | jq -r '.fields[].name')
    if test -z "$field_names"
        echo (set_color red)"Error: no custom fields on Bitwarden item 'API Keys'"(set_color normal)
        bw lock --session "$BW_SESSION" >/dev/null 2>&1
        set -e BW_SESSION
        return 1
    end

    echo "Syncing environment variables from Bitwarden:"
    for key in $field_names
        echo "  - $key"
    end

    set -l persist_dir "$HOME/.config/fish/conf.d"
    set -l persist_file "$persist_dir/env-sync-vars.fish"

    if not test -d $persist_dir
        mkdir -p $persist_dir
    end

    umask 077
    echo "# Auto-generated by env-sync - do not edit manually" >$persist_file
    echo "# Synced on "(date) >>$persist_file
    chmod 600 $persist_file

    # Iterate without a pipe so set -gx applies to this shell
    for row in (echo $item_json | jq -c '.fields[]')
        set -l var_name (echo $row | jq -r '.name')
        set -l var_value (echo $row | jq -r '.value')

        set -l exists false
        set -l needs_update false

        if set -q $var_name
            set exists true
            set -l current_value $$var_name
            if test "$current_value" != "$var_value"
                set needs_update true
            end
        end

        if test "$exists" = "false"
            set -gx $var_name $var_value
            echo "  Set: $var_name"
        else if test "$needs_update" = "true"
            set -gx $var_name $var_value
            echo "  Updated (value changed): $var_name"
        else if test "$force_overwrite" = "true"
            set -gx $var_name $var_value
            echo "  Refreshed: $var_name"
        else
            echo "  Skipped (unchanged): $var_name"
        end

        set -l escaped_value (string escape -- $var_value)
        echo "set -gx $var_name $escaped_value" >>$persist_file
    end

    echo "Variables persisted to: $persist_file"

    bw lock --session "$BW_SESSION" >/dev/null 2>&1
    set -e BW_SESSION

    echo "Environment sync complete!"
end
