#!/usr/bin/env bash
# Portable env-sync: fetch API keys from Bitwarden and emit shell-specific
# assignment code on stdout.  Thin per-shell wrappers eval stdout.
#
# Usage:  env-sync.sh [--shell fish|zsh] [-f|--force] [-h|--help]
#
# NOTE: Values containing newlines are not supported (API keys don't need them).

set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────────

info()  { printf '%s\n' "$*" >&2; }
err()   { printf 'Error: %s\n' "$*" >&2; }

# Escape a value for fish:  set -gx NAME 'value'
# Fish single-quote rules: backslash → \\   single-quote → \'
fish_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g" | { IFS= read -r v; printf "'%s'" "$v"; }
}

# Escape a value for POSIX/zsh:  export NAME='value'
# POSIX rule: single-quote → '\''
posix_escape() {
  printf '%s' "$1" | sed "s/'/'\\\\''/g" | { IFS= read -r v; printf "'%s'" "$v"; }
}

# ── Argument parsing ─────────────────────────────────────────────────────────

SHELL_TYPE=""
FORCE=0

usage() {
  cat >&2 <<'EOF'
Sync API keys from Bitwarden to environment

Usage: env-sync [options]

Options:
  --shell fish|zsh  Target shell (default: auto-detect from $SHELL)
  -f, --force       Force refresh all variables (even unchanged)
  -h, --help        Show this help message

Behavior:
  - New variables: Always set
  - Changed values: Auto-updated (smart sync)
  - Unchanged values: Skipped (use --force to refresh)
  - Values persisted for new shells:
      fish → ~/.config/fish/conf.d/env-sync-vars.fish
      zsh  → ~/.config/zsh/env-sync-vars.zsh
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --shell)  SHELL_TYPE="${2:-}"; shift 2 ;;
    -f|--force) FORCE=1; shift ;;
    -h|--help)  usage ;;
    *) err "Unknown option: $1"; exit 1 ;;
  esac
done

# Default shell detection
if [[ -z "$SHELL_TYPE" ]]; then
  SHELL_TYPE="$(basename "${SHELL:-bash}")"
fi

case "$SHELL_TYPE" in
  fish|zsh) ;;
  *) err "Unsupported shell: $SHELL_TYPE (use fish or zsh)"; exit 1 ;;
esac

# ── Emit helpers (write eval-able code to stdout) ────────────────────────────

# Emit a single assignment line for the target shell.
emit_assign() {
  local name="$1" value="$2"
  case "$SHELL_TYPE" in
    fish) printf 'set -gx %s %s\n' "$name" "$(fish_escape "$value")" ;;
    zsh)  printf 'export %s=%s\n'   "$name" "$(posix_escape "$value")" ;;
  esac
}

# Emit an unset line for the target shell.
emit_unset() {
  local name="$1"
  case "$SHELL_TYPE" in
    fish) printf 'set -e %s\n' "$name" ;;
    zsh)  printf 'unset %s\n'  "$name" ;;
  esac
}

# ── Dependency checks ────────────────────────────────────────────────────────

if ! command -v bw >/dev/null 2>&1; then
  err "Bitwarden CLI (bw) not found"; exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  err "jq not found"; exit 1
fi

# ── Bitwarden unlock ─────────────────────────────────────────────────────────

if [[ -z "${BW_SESSION:-}" ]]; then
  info "Unlocking Bitwarden"
  # stdin stays attached to the terminal (only stdout is captured by the
  # calling wrapper's eval/source), so the master-password prompt works.
  BW_SESSION="$(bw unlock --raw)" || true
  if [[ -z "$BW_SESSION" ]]; then
    err "Failed to unlock Bitwarden"; exit 1
  fi
  # Emit the session into the caller's environment so subsequent manual
  # invocations within the same shell session don't re-prompt (it will be
  # unset again at the end).
  emit_assign BW_SESSION "$BW_SESSION"
  export BW_SESSION
fi

# ── Fetch item ───────────────────────────────────────────────────────────────

item_json="$(bw get item "API Keys" --session "$BW_SESSION" 2>/dev/null)" || true
if [[ -z "$item_json" ]]; then
  err "Could not read Bitwarden item 'API Keys'"
  bw lock --session "$BW_SESSION" >/dev/null 2>&1 || true
  emit_unset BW_SESSION
  exit 1
fi

field_names="$(printf '%s' "$item_json" | jq -r '.fields[].name' 2>/dev/null)" || true
if [[ -z "$field_names" ]]; then
  err "No custom fields on Bitwarden item 'API Keys'"
  bw lock --session "$BW_SESSION" >/dev/null 2>&1 || true
  emit_unset BW_SESSION
  exit 1
fi

# ── Sync variables ───────────────────────────────────────────────────────────

info "Syncing environment variables from Bitwarden:"
while IFS= read -r key; do
  info "  - $key"
done <<< "$field_names"

# Determine persist file
case "$SHELL_TYPE" in
  fish) persist_dir="$HOME/.config/fish/conf.d"
        persist_file="$persist_dir/env-sync-vars.fish" ;;
  zsh)  persist_dir="$HOME/.config/zsh"
        persist_file="$persist_dir/env-sync-vars.zsh" ;;
esac
mkdir -p "$persist_dir"

# Write persist header (mode 600)
old_umask="$(umask)"
umask 077
printf '# Auto-generated by env-sync - do not edit manually\n' > "$persist_file"
printf '# Synced on %s\n' "$(date)" >> "$persist_file"
chmod 600 "$persist_file"
umask "$old_umask"

# stdout comment so the eval stream is annotated
printf '# env-sync assignments\n'

# Iterate over fields
while IFS= read -r row; do
  var_name="$(printf '%s' "$row" | jq -r '.name')"
  var_value="$(printf '%s' "$row" | jq -r '.value')"

  current_value="$(printenv "$var_name" 2>/dev/null)" || true
  exists=false
  needs_update=false

  if [[ -n "${current_value+set}" ]] && printenv "$var_name" >/dev/null 2>&1; then
    exists=true
    if [[ "$current_value" != "$var_value" ]]; then
      needs_update=true
    fi
  fi

  if [[ "$exists" == "false" ]]; then
    emit_assign "$var_name" "$var_value"
    info "  Set: $var_name"
  elif [[ "$needs_update" == "true" ]]; then
    emit_assign "$var_name" "$var_value"
    info "  Updated (value changed): $var_name"
  elif [[ "$FORCE" -eq 1 ]]; then
    emit_assign "$var_name" "$var_value"
    info "  Refreshed: $var_name"
  else
    info "  Skipped (unchanged): $var_name"
  fi

  # Always persist (all fields go to the file regardless of skip)
  case "$SHELL_TYPE" in
    fish) printf 'set -gx %s %s\n' "$var_name" "$(fish_escape "$var_value")" >> "$persist_file" ;;
    zsh)  printf 'export %s=%s\n'   "$var_name" "$(posix_escape "$var_value")" >> "$persist_file" ;;
  esac
done < <(printf '%s' "$item_json" | jq -c '.fields[]')

info "Variables persisted to: $persist_file"

# ── Cleanup ──────────────────────────────────────────────────────────────────

bw lock --session "$BW_SESSION" >/dev/null 2>&1 || true
emit_unset BW_SESSION

info "Environment sync complete!"
